config/routes.rb
Rails.application.routes.draw do

  resources :student_evaluation_forms
  resources :overseer_evaluation_forms
  get 'dashboard' => 'dashboard#index'
  get 'event/calendar' => 'events#calendar'
  get 'master_clinical_log' => 'events#master_clinical_log'
  get 'event/list' => 'events#list'
  get 'event/todo' => 'events#todo'
  get 'events/:id/login'  => 'events#login', as: :events_login
  patch 'events/:id/login'  => 'events#login_update', as: :events_login_update
  get 'events/:id/logout'  => 'events#logout', as: :events_logout
  patch 'events/:id/logout'  => 'events#logout_update', as: :events_logout_update
  get 'skills/:id/level_up'  => 'skills#level_up', as: :skills_level_up
  patch 'skills/:id/level_up'  => 'skills#level_up_update', as: :skills_level_up_update

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
      post :mark_as_unread
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]

  match "/event/calendar/:year/:month", :to => "events#calendar", via: [:get, :post],
        :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ },
        :as => 'events_calendar'

  match "/event/list/:year/:month/:day", :to => "events#list", via: [:get, :post],
        :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ , :day => /\d{1,2}/},
        :as => 'events_list_day'

  match "/event/list/:year/:month", :to => "events#list", via: [:get, :post],
        :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ },
        :as => 'events_list_month'

  match "/event/list/:year", :to => "events#list", via: [:get, :post],
        :constraints => { :year => /\d{4}/},
        :as => 'events_list_year'
  resources :courses
  resources :time_courses
  resources :programs
  resources :events
  resources :defined_courses
  resources :contacts, path: '/profile/contacts'
  resources :skills
  resources :defined_skills
  resources :locations  do
    get :autocomplete, :on => :collection
  end
  resources :links
  devise_for :users, path: '/profile', :controllers => {:registrations => "registrations"}
  resources :users do
    get :autocomplete, :on => :collection
    get :autocomplete_student, :on => :collection
    get :autocomplete_overseer, :on => :collection
    get :autocomplete_faculty, :on => :collection
  end

  resources :notes do
    member do
      get 'download'
    end
  end
  devise_scope :user do
    authenticated :user do
      root 'events#calendar', as: :authenticated_root
      root :to => 'events#calendar'

    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :title
  validates_presence_of :body
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy, :download]

  # GET /notes
  def index
    @notes = current_user.notes.order('updated_at DESC').page(params[:page]).per(8)
  end

  # GET /notes/1
  def show
    check_ownership(@note)
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
    check_ownership(@note)
  end

  def download
    check_ownership(@note)
    body = @note.body
    send_data body, :filename => "#{@note.title}.txt", :disposition => 'attachment'
  end

  # POST /notes
  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    if @note.save
      redirect_to notes_url, notice: 'Note was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /notes/1
  def update
    check_ownership(@note)
    if @note.update(note_params)
      redirect_to notes_url, notice: 'Note was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /notes/1
  def destroy
    check_ownership(@note)
    @note.destroy
    redirect_to notes_url, notice: 'Note was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def note_params
      params.require(:note).permit(:title, :body, :user_id, :background_color)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.haml
- content_for :title, t('notes')
.page-header
  %h2= t('notes')
= form_for @note, html: {id: :notes }  do |f|
  - if @note.errors.any?
    #error_explanation
      %h2= "#{pluralize(@note.errors.count, "error")} prohibited this note from being saved:"
      %ul
        - @note.errors.full_messages.each do |msg|
          %li= msg

  .button-group.btn-group-justified
    = link_to "", {}, id: "save", :class => "btn btn-lg btn-primary navbar-btn glyphicon glyphicon-saved"
    = link_to "", notes_path, :class => "btn btn-lg btn-primary navbar-btn glyphicon glyphicon-remove-sign"
    .btn.btn-primary.navbar-btn
      = f.color_field :background_color
  %p

  .field
    = f.text_field :title, :class => "form-control input", :placeholder => t('title')
  .field
    = f.text_area :body, :class => "form-control lg-input"
  .actions
    = f.submit 'Save', :style => "display: none;"

:javascript
  $(document).ready(function() {
  $('#save').on('click', function() { $('#notes').submit(); });
  });

app/views/notes/edit.html.haml
= render 'form'

/= link_to 'Show', @note
/\|
/= link_to 'Back', notes_path

app/views/notes/index.html.haml
- content_for :title, t('notes')
.page-header
  %h2= t('notes')
.btn-group-justified
  =link_to( '', new_note_path,:class => "btn btn-lg btn-primary glyphicon glyphicon-plus-sign")
%center
  .center
    %nav{"aria-label" => "..."}
      %ul.pager
        %li.previous
          = link_to_previous_page @notes, "<i class='glyphicon glyphicon-chevron-left'></i> #{t('previous')}".html_safe
        %li.next
          =link_to_next_page @notes, "#{t('next')}<i class='glyphicon glyphicon-chevron-right'></i>".html_safe

%p
- @notes.each_slice(2) do |note2|
  .row
    -note2.each do |note|
      .col-xs-6.col-ms-6.col-lg-6
        .child{:style => "background-color: #{note.background_color};"}
          .row
            .col-xs-12.col-lg-4
              = link_to '', edit_note_path(note), :class => "btn btn-default glyphicon glyphicon-edit"
              = link_to '', download_note_path(note), :method => :get, :class => "btn btn-default glyphicon glyphicon-download"
              = link_to '', note, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn btn-danger glyphicon glyphicon-trash"
              \ 
              %p
            .col-xs-12.col-lg-8
              .truncate
                %p
                %h4{:style => "color: #{note.background_color};filter: invert(100%);"}
                  = note.title
          .row
            .col-xs-12{:style => "color: #{note.background_color};filter: invert(100%);"}= note.body.html_safe

app/views/notes/new.html.haml
= render 'form'

app/views/notes/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @note.title
%p
  %b Body:
  = @note.body
%p
  %b User:
  = @note.user

= link_to 'Edit', edit_note_path(@note)
\|
= link_to 'Back', notes_path