config/routes.rb
Rails.application.routes.draw do

  resources :student_evaluation_forms
  resources :overseer_evaluation_forms
  get 'dashboard' => 'dashboard#index'
  get 'event/calendar' => 'events#calendar'
  get 'master_clinical_log' => 'events#master_clinical_log'
  get 'event/list' => 'events#list'
  get 'event/todo' => 'events#todo'
  get 'events/:id/login'  => 'events#login', as: :events_login
  patch 'events/:id/login'  => 'events#login_update', as: :events_login_update
  get 'events/:id/logout'  => 'events#logout', as: :events_logout
  patch 'events/:id/logout'  => 'events#logout_update', as: :events_logout_update
  get 'skills/:id/level_up'  => 'skills#level_up', as: :skills_level_up
  patch 'skills/:id/level_up'  => 'skills#level_up_update', as: :skills_level_up_update

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
      post :mark_as_unread
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]

  match "/event/calendar/:year/:month", :to => "events#calendar", via: [:get, :post],
        :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ },
        :as => 'events_calendar'

  match "/event/list/:year/:month/:day", :to => "events#list", via: [:get, :post],
        :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ , :day => /\d{1,2}/},
        :as => 'events_list_day'

  match "/event/list/:year/:month", :to => "events#list", via: [:get, :post],
        :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ },
        :as => 'events_list_month'

  match "/event/list/:year", :to => "events#list", via: [:get, :post],
        :constraints => { :year => /\d{4}/},
        :as => 'events_list_year'
  resources :courses
  resources :time_courses
  resources :programs
  resources :events
  resources :defined_courses
  resources :contacts, path: '/profile/contacts'
  resources :skills
  resources :defined_skills
  resources :locations  do
    get :autocomplete, :on => :collection
  end
  resources :links
  devise_for :users, path: '/profile', :controllers => {:registrations => "registrations"}
  resources :users do
    get :autocomplete, :on => :collection
    get :autocomplete_student, :on => :collection
    get :autocomplete_overseer, :on => :collection
    get :autocomplete_faculty, :on => :collection
  end

  resources :notes do
    member do
      get 'download'
    end
  end
  devise_scope :user do
    authenticated :user do
      root 'events#calendar', as: :authenticated_root
      root :to => 'events#calendar'

    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    @conversations = @conversations.page(params[:page]).per(8)
  end

  def show
    @conversation.mark_as_read(current_user)
  end

  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

    def mark_as_unread
    @conversation.mark_as_unread(current_user)
    flash[:success] = 'The conversation was marked as unread.'
    redirect_to conversations_path
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

  def get_box
    if params[:box]
      session[:box] = params[:box]
    end
    if session[:box].blank? or !["inbox","sent","trash"].include?(session[:box])
      session[:box] = params[:box] = 'inbox'
    end
    @box = session[:box]
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(('<span>&nbsp;&nbsp;&nbsp;'+glyph("#{title.to_s == 'sent' ? 'send' : title}".to_sym) + '&nbsp;&nbsp;&nbsp;</span>').html_safe, conversations_path(box: title.downcase), class: "btn btn-lg"), opts
  end
end

app/views/conversations/_conversation.html.haml
%li.list-group-item.clearfix
  = link_to conversation.subject, conversation_path(conversation), class: 'btn btn-lg btn-block'
  .btn-group-vertical.pull-right
    - if conversation.is_trashed?(current_user)
      = link_to '', restore_conversation_path(conversation), class: 'btn btn-lg btn-block btn-primary glyphicon glyphicon-repeat', method: :post
    - else                                                                           |
      - if conversation.is_unread?(current_user)
        = link_to '', mark_as_read_conversation_path(conversation),  class: 'btn btn-lg btn-block glyphicon glyphicon-unchecked btn-primary', method: :post
      -else
        = link_to '', mark_as_unread_conversation_path(conversation),  class: 'btn btn-lg btn-block glyphicon glyphicon-check btn-primary', method: :post
      = link_to '', conversation_path(conversation), class: 'btn btn-lg btn-danger btn-block glyphicon glyphicon-trash', method: :delete, data: {confirm: 'Are you sure?'}
  %p= render 'conversations/participants', conversation: conversation
  %p
    = conversation.last_message.body
    %small
      (
      %span.text-muted>= l conversation.last_message.created_at, format: :long
      )

app/views/conversations/_participants.html.haml
- conversation.participants.each do |participant|
  - unless participant == current_user
    .row
      .col-lg-12.col-md-12.col-sm-12.col-xs-12
        = (glyph(:pencil) + ' ' + participant.identifier) unless participant.nil?

app/views/conversations/index.html.haml
-content_for :title, t('conversations')
.page-header
  %h2= t('conversations')
.btn-group-justified
  =link_to( '', new_message_path,:class => "btn btn-lg btn-primary glyphicon glyphicon-plus-sign")
  = link_to '', empty_trash_conversations_path, class: 'btn btn-lg btn-danger glyphicon glyphicon-trash', method: :delete, |
          data: {confirm: t('empty_trash')}
%p
%center
  .center
    %ul.nav.nav-tabs
      = mailbox_section 'inbox', @box
      = mailbox_section 'sent', @box
      = mailbox_section 'trash', @box
    %nav{"aria-label" => "..."}
      %ul.pager
        %li.previous
          = link_to_previous_page @conversations, "<i class='glyphicon glyphicon-chevron-left'></i> #{t('previous')}".html_safe
        %li.next
          =link_to_next_page @conversations, "#{t('next')}<i class='glyphicon glyphicon-chevron-right'></i>".html_safe
%ul.list-group
  = render partial: 'conversations/conversation', collection: @conversations

app/views/conversations/show.html.haml
-content_for :title, t('reply_conversation')
.page-header
  %h2= t('reply_conversation')
%p
  \#{render 'conversations/participants', conversation: @conversation}
.panel.panel-default
  .panel-heading= @conversation.subject
  .panel-body
    .messages
      - @conversation.receipts_for(current_user).each do |receipt|
        .media
          - message = receipt.message
          .media-left
            = ""
          .media-body
            %h6.media-heading
              = message.sender.name
              =l message.created_at, format: :long
            = message.body
= form_tag reply_conversation_path(@conversation), :id => 'message', method: :post do
  .button-group.btn-group-justified
    = link_to "", {}, id: "save", :class => "btn btn-lg btn-primary navbar-btn glyphicon glyphicon-send"
    = link_to "", conversations_path, :class => "btn btn-lg btn-primary navbar-btn glyphicon glyphicon-remove-sign"
  %p
  .form-group
    = label_tag 'message[body]', 'Message'
    = text_area_tag 'body', nil, cols: 3, class: 'form-control', required: true
  = submit_tag 'Send', :style => "display: none;"


:javascript
  $(document).ready(function() {
  $('#save').on('click', function() { $('#message').submit(); });
  });