config/routes.rb
Rails.application.routes.draw do

  resources :student_evaluation_forms
  resources :overseer_evaluation_forms
  get 'dashboard' => 'dashboard#index'
  get 'event/calendar' => 'events#calendar'
  get 'master_clinical_log' => 'events#master_clinical_log'
  get 'event/list' => 'events#list'
  get 'event/todo' => 'events#todo'
  get 'events/:id/login'  => 'events#login', as: :events_login
  patch 'events/:id/login'  => 'events#login_update', as: :events_login_update
  get 'events/:id/logout'  => 'events#logout', as: :events_logout
  patch 'events/:id/logout'  => 'events#logout_update', as: :events_logout_update
  get 'skills/:id/level_up'  => 'skills#level_up', as: :skills_level_up
  patch 'skills/:id/level_up'  => 'skills#level_up_update', as: :skills_level_up_update

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
      post :mark_as_unread
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]

  match "/event/calendar/:year/:month", :to => "events#calendar", via: [:get, :post],
        :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ },
        :as => 'events_calendar'

  match "/event/list/:year/:month/:day", :to => "events#list", via: [:get, :post],
        :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ , :day => /\d{1,2}/},
        :as => 'events_list_day'

  match "/event/list/:year/:month", :to => "events#list", via: [:get, :post],
        :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ },
        :as => 'events_list_month'

  match "/event/list/:year", :to => "events#list", via: [:get, :post],
        :constraints => { :year => /\d{4}/},
        :as => 'events_list_year'
  resources :courses
  resources :time_courses
  resources :programs
  resources :events
  resources :defined_courses
  resources :contacts, path: '/profile/contacts'
  resources :skills
  resources :defined_skills
  resources :locations  do
    get :autocomplete, :on => :collection
  end
  resources :links
  devise_for :users, path: '/profile', :controllers => {:registrations => "registrations"}
  resources :users do
    get :autocomplete, :on => :collection
    get :autocomplete_student, :on => :collection
    get :autocomplete_overseer, :on => :collection
    get :autocomplete_faculty, :on => :collection
  end

  resources :notes do
    member do
      get 'download'
    end
  end
  devise_scope :user do
    authenticated :user do
      root 'events#calendar', as: :authenticated_root
      root :to => 'events#calendar'

    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :overseer, foreign_key: 'overseer_id', class_name: 'User'
  belongs_to :student, foreign_key: 'student_id', class_name: 'User'
  belongs_to :course, foreign_key: 'course_id', class_name: 'TimeCourse'
  belongs_to :location
  has_one :overseer_evaluation_form
  has_one :student_evaluation_form
  validates_presence_of :student
  validates_presence_of :overseer
  validates_presence_of :location
  validates_presence_of :course
  validates_presence_of :start
  validates_presence_of :stop

  def ended?
    !login.nil? && !logout.nil? && stop > DateTime.now
  end
end

app/controllers/events_controller.rb
# coding: utf-8
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :login, :logout, :login_update, :logout_update]
  before_action :has_power?, only: [:new, :show, :edit, :update, :destroy]
  before_action :define_time_courses, only: [:new, :edit, :update, :create]

  def list
    if params[:day] && Date.valid_date?(params[:year].to_i, params[:month].to_i, params[:day].to_i)
      @current = Date.new(params[:year].to_i, params[:month].to_i, params[:day].to_i)
      @older = @current - 1.day
      @newer = @current + 1.day
      if current_user.has_power?
        @events = Event.where("cast(extract(year from start) as int) = ? and cast(extract(month from start) as int) = ? and cast(extract(day from start) as int) = ?", @current.year, @current.month, @current.day).group_by{ |item| item.start.to_date }
      else
        @events = Event.where("(student_id LIKE #{current_user.id} OR overseer_id LIKE #{current_user.id}) and cast(extract(year from start) as int) = ? and cast(extract(month from start) as int) = ? and cast(extract(day from start) as int) = ?", @current.year, @current.month, @current.day).group_by{ |item| item.start.to_date }
      end
    elsif params[:month] && Date.valid_date?(params[:year].to_i, params[:month].to_i,1)
      @current = Date.new(params[:year].to_i, params[:month].to_i)
      @older = @current - 1.month
      @newer = @current + 1.month
      if current_user.has_power?
        @events = Event.where("cast(extract(year from start) as int) = ? and cast(extract(month from start) as int) = ?", @current.year, @current.month).group_by{ |item| item.start.to_date }
      else
        @events = Event.where("(student_id LIKE #{current_user.id} OR overseer_id LIKE #{current_user.id}) and cast(extract(year from start) as int) = ? and cast(extract(month from start) as int) = ?", @current.year, @current.month).group_by{ |item| item.start.to_date }
      end
    elsif params[:year] && !params[:month] && Date.valid_date?(params[:year].to_i, 1,1)
      @current = Date.new(params[:year].to_i)
      @older = @current - 1.year
      @newer = @current + 1.year
      if current_user.has_power?
        @events = Event.where("cast(extract(year from start) as int) = ?", @current.year).group_by{ |item| item.start.to_date }
      else
        @events = Event.where("(student_id LIKE #{current_user.id} OR overseer_id LIKE #{current_user.id}) and cast(extract(year from start) as int) = ?", @current.year).group_by{ |item| item.start.to_date }
      end
    else
      @current = Date.today
      @older = @current - 1.month
      @newer = @current + 1.month
       if current_user.has_power?
         @events = Event.all.group_by{ |item| item.start.to_date }
       else
         @events = Event.where("student_id LIKE #{current_user.id} OR overseer_id LIKE #{current_user.id}").group_by{ |item| item.start.to_date }
       end
    end

  end

  def calendar
    if current_user.has_power?
      @events = Event.all.group_by{ |item| item.start.to_date }
    else
      @events = Event.where("student_id LIKE #{current_user.id} OR overseer_id LIKE #{current_user.id}").group_by{ |item| item.start.to_date }
    end

    if params[:month] && Date.valid_date?(params[:year].to_i, params[:month].to_i,1)
      @current = Date.new(params[:year].to_i, params[:month].to_i)
    else
      @current = Date.today
    end
    @older = @current - 1.month
    @newer = @current + 1.month
  end

  def master_clinical_log
    @master_clinical_logs = Event.all.page(params[:page]).per(16)
  end

  def todo
    if current_user.has_power?
      @events = Event.where("(login IS NULL OR logout IS NULL) OR stop > ?", DateTime.now).order('start DESC')
    else
      @events = Event.where("(student_id LIKE #{current_user.id} OR overseer_id LIKE #{current_user.id}) AND ((login IS NULL OR logout IS NULL) OR stop > ?)", DateTime.now).order('start DESC')
    end
  end


  def login
  end

  def login_update
    if (@event.overseer.pin.to_i == params[:pin].to_i)
      @event.update(event_params)
      redirect_to events_list_day_path(@event.start.year,@event.start.month, @event.start.day), notice: 'Event, login successful'
    else
      respond_to do |format|
        format.html {
          flash[:alert] = 'Invalid Pin'
          render :login
        }
      end
    end
  end

  def logout
  end

  def logout_update
    if (@event.overseer.pin.to_i == params[:pin].to_i)
      @event.update(event_params)
      redirect_to events_list_day_path(@event.start.year,@event.start.month, @event.start.day), notice: 'Event logout, successful'
    else
      respond_to do |format|
        format.html {
          flash[:alert] = 'Invalid Pin'
          render :logout
        }
      end
    end
  end

  # GET /events
  def index
    redirect_to event_calendar_path
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to events_list_day_path(@event.start.year,@event.start.month, @event.start.day), notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to events_list_day_path(@event.start.year,@event.start.month, @event.start.day), notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to event_calendar_path, notice: 'Event was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def event_params
      params.require(:event).permit(:overseer_id, :student_id, :course_id, :start, :stop, :login, :logout, :location_id)
    end

    def define_time_courses
      @time_courses = TimeCourse.all.inject({}) do |options, course|
        (options[ course.course.identifier] ||= []) << [course.identifier, course.id]
        options
      end
    end
end

app/helpers/events_helper.rb
module EventsHelper
  def within(event)
    now = DateTime.now
    result = 'default'
    # login on time
    if event.login && (event.start + 15.minutes) > event.login && event.login > (event.start - 15.minutes)
      result = 'success'

      # logout on time
      if event.logout && (event.stop + 15.minutes) > event.logout && event.logout > (event.stop - 15.minutes)
        result = 'success'
        # logged out but late
      elsif event.logout && !((event.stop + 15.minutes) > event.logout && event.logout > (event.stop - 15.minutes))
        result = 'danger'
      # not logged out and safe to
      elsif event.logout.nil? && (event.stop + 15.minutes) > now && now > (event.stop - 15.minutes)
        result = 'warning'
      # not logged out and late
      elsif event.logout.nil? && (event.stop + 15.minutes) < now
        result = 'danger'
      end
      # logged in but late
    elsif event.login && !((event.start + 15.minutes) > event.login && event.login > (event.start - 15.minutes))
      result = 'danger'
    # not logged in and safe to
    elsif event.login.nil? && (event.start + 15.minutes) > now && now > (event.start - 15.minutes)
      result = 'warning'
    # not logged in and late
    elsif event.login.nil? && (event.start + 15.minutes) < now
      result = 'danger'
    end

    result
  end


  def time_diff(start_time, end_time)
    seconds_diff = (start_time - end_time).to_i.abs

    hours = seconds_diff / 3600
    seconds_diff -= hours * 3600

    minutes = seconds_diff / 60
    #seconds_diff -= minutes * 60

    #seconds = seconds_diff

    "#{hours.to_s} hr #{minutes.to_s} min"
  end
end

app/views/events/_event.html.haml
- @now = DateTime.now()
.panel{:class => "panel-#{within(event)}"}
  .panel-heading.clearfix
    .row
      .col-lg-6.col-md-6.col-sm-6.col-xs-6
        -if current_user.has_power?
          = link_to '', edit_event_path(event), :class => "btn btn-default btn-lg btn-block glyphicon glyphicon-edit"
        %p
      .col-lg-6.col-md-6.col-sm-6.col-xs-6
        -if current_user.has_power?
          = link_to '', event, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn btn-lg btn-block btn-danger glyphicon glyphicon-trash"
        %p
    .row
      .col-lg-6.col-md-6.col-sm-6.col-xs-6
        =t('activerecord.attributes.event.start')
      .col-lg-6.col-md-6.col-sm-6.col-xs-6
        =t('activerecord.attributes.event.stop')
    .row
      .col-lg-6.col-md-6.col-sm-6.col-xs-6
        = l event.start, format: :long
      .col-lg-6.col-md-6.col-sm-6.col-xs-6
        = l event.stop, format: :long
  .panel-body
    .row
      .col-lg-6.col-md-6.col-sm-6.col-xs-6
        =t('activerecord.attributes.event.student')
      .col-lg-6.col-md-6.col-sm-6.col-xs-6
        =t('activerecord.attributes.event.overseer')
    .row
      .col-lg-6.col-md-6.col-sm-6.col-xs-6
        =link_to(event.student.name, user_path(event.student)) unless event.student.nil?
        %p
      .col-lg-6.col-md-6.col-sm-6.col-xs-6
        =link_to(event.overseer.name, user_path(event.overseer)) unless event.overseer.nil?
        %p
    -if (@now > (event.stop - 15.minutes))
      .row
        .col-lg-6.col-md-6.col-sm-6.col-xs-6
          -if event.student && event.overseer
            -if current_user.id == event.overseer.id
              =link_to t('evaluate'),  (event.student_evaluation_form.nil? ? new_student_evaluation_form_path(event: event.id, student: event.student.id) : edit_student_evaluation_form_path(event.student_evaluation_form)), class: "btn btn-default btn-lg btn-block"
            -elsif current_user.has_power? && event.student_evaluation_form
              = link_to t('evaluate'), event.student_evaluation_form, class: "btn btn-default btn-lg btn-block"
        .col-lg-6.col-md-6.col-sm-6.col-xs-6
          -if event.overseer && event.student
            -if current_user.id == event.student.id
              =link_to t('evaluate'),  (event.overseer_evaluation_form.nil? ? new_overseer_evaluation_form_path(event: event.id, overseer: event.overseer.id) : edit_overseer_evaluation_form_path(event.overseer_evaluation_form)), class: "btn btn-default btn-lg btn-block"
            -elsif current_user.has_power? && event.overseer_evaluation_form
              = link_to t('evaluate'), event.overseer_evaluation_form, class: "btn btn-default btn-lg btn-block"
    .row
      .col-lg-6.col-md-6.col-sm-6.col-xs-6
        =t('activerecord.attributes.event.login')
      .col-lg-6.col-md-6.col-sm-6.col-xs-6
        =t('activerecord.attributes.event.logout')
    .row
      .col-lg-6.col-md-6.col-sm-6.col-xs-6
        %p
        -if event.login.nil?
          =link_to '', events_login_path(event), :class => "btn btn-default btn-lg btn-block glyphicon glyphicon-log-in"
        = l event.login, format: :long unless event.login.nil?
        %p
      .col-lg-6.col-md-6.col-sm-6.col-xs-6
        %p
        -if event.logout.nil?
          =link_to '', events_logout_path(event), :class => "btn btn-default btn-lg btn-block glyphicon glyphicon-log-out"
        = l event.logout, format: :long unless event.logout.nil?
      %p
    .row
      .col-lg-12.col-md-12.col-sm-12.col-xs-12
        = t('course')
      .col-lg-12.col-md-12.col-sm-12.col-xs-12
        = event.course.full_id unless event.course.nil?
    %p
    .row
      .col-lg-12.col-md-12.col-sm-12.col-xs-12
        =t('activerecord.attributes.event.location')
      .col-lg-12.col-md-12.col-sm-12.col-xs-12
        = link_to(event.location.identifier, event.location.googlemaps, :target => "_blank") unless event.location.nil?

app/views/events/_form.html.haml
-content_for :title, t('event')
.page-header
  %h2= t('event')
= form_for @event, html: {id: :event, locale: current_user.language  } do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .button-group.btn-group-justified
    = link_to "", {}, id: "save", :class => "btn btn-lg btn-primary navbar-btn glyphicon glyphicon-saved"
    = link_to "", event_calendar_path, :class => "btn btn-lg btn-primary navbar-btn glyphicon glyphicon-remove-sign"
  %p
  .field
    = f.label :overseer
    = f.autocomplete_field :overseer, autocomplete_overseer_users_path,fields: { overseer: "#overseer" }, :id_element => "#event_overseer_id", :update_elements => {}, :class => "form-control input", :value => (@event.overseer.identifier unless @event.overseer.nil?)
    = f.hidden_field :overseer_id
    %p
  .field
    = f.label :student
    = f.autocomplete_field :student, autocomplete_student_users_path,fields: { student: "#student" }, :id_element => "#event_student_id", :update_elements => {}, :class => "form-control input", :value => (@event.student.identifier unless @event.student.nil?)
    = f.hidden_field :student_id
    %p
  .field
    .form-group
      = f.label :course
      = f.select :course_id, @time_courses,{ include_blank: true},{ class: 'form-control input chosen-it' }
    %p
  .field
    = f.label :start
    = f.datetime_select :start, locale: current_user.language
    %p
  .field
    = f.label :stop
    = f.datetime_select :stop, locale: current_user.language
    %p
  .field
    = f.label :login
    = f.datetime_select :login, locale: current_user.language
    %p
  .field
    = f.label :logout
    = f.datetime_select :logout, locale: current_user.language
    %p
  .field
    = f.label :location
    = f.autocomplete_field :location, autocomplete_locations_path, fields: { location: "#location" }, :id_element => "#event_location_id", :update_elements => {}, :class => "form-control input", :value => (@event.location.identifier unless @event.location.nil?)
    = f.hidden_field :location_id
  .field
    = f.submit 'Save', :style => "display: none;"

:javascript
  $(document).ready(function() {
  $('#save').on('click', function() { $('#event').submit(); });
  });

app/views/events/_toolbar.html.haml
.btn-group-justified
  -if current_user.has_power?
    = link_to( '', new_event_path,:class => "btn btn-lg btn-primary glyphicon glyphicon-plus-sign")
  = link_to('', events_calendar_path(@current.year, @current.month),:class => "btn btn-lg btn-primary glyphicon glyphicon-calendar")
  = link_to('', events_list_month_path(@current.year, @current.month),:class => "btn btn-lg btn-primary glyphicon glyphicon-list")
  = link_to('', event_todo_path, :class => 'btn btn-lg btn-primary glyphicon glyphicon-list-alt')

app/views/events/calendar.html.haml
-content_for :title, t('events') + " | " +  l(@current, format: :year_month)
.page-header
  %h2= l @current, format: :year_month
= render 'toolbar'
%center
  .center
    %nav{"aria-label" => "..."}
      %ul.pager
        %li.previous
          %a{:href => events_calendar_path(@older.year, @older.month)}
            .glyphicon.glyphicon-chevron-left
            =t('previous')
        %li.next
          %a{:href => events_calendar_path(@newer.year,@newer.month)}
            =t('next')
            .glyphicon.glyphicon-chevron-right
= bootstrap_calendar @current do |date|
  =date.day
  =link_to @events[date].nil? ? events_list_day_path(@current.year,@current.month, date.day) :events_list_day_path(@events[date].first.start.year,@events[date].first.start.month, @events[date].first.start.day) do
    .cal-box
      -if @events[date]
        %center
          %h3= @events[date].count
      -else
        %center
          %h3 &nbsp;
      %br
      %br

app/views/events/edit.html.haml
= render 'form'

app/views/events/list.html.haml
-if params[:day]
  -content_for :title, t('events') + " | " +  l(@current, format: :long)
  .page-header
    %h2= l @current, format: :long
-elsif params[:year] && !params[:month]
  -content_for :title, t('events') + " | " +  l(@current, format: :year_month)
  .page-header
    %h2= l @current, format: :year
-else
  -content_for :title, t('events') + " | " +  l(@current, format: :year_month)
  .page-header
    %h2= l @current, format: :year_month

= render 'toolbar'
%center
  .center
    %nav{"aria-label" => "..."}
      %ul.pager
        %li.previous
          -if params[:day]
            %a{:href => events_list_day_path(@older.year, @older.month, @older.day)}
              .glyphicon.glyphicon-chevron-left
              =t('previous')
          -elsif params[:year] && !params[:month]
            %a{:href => events_list_year_path(@older.year)}
              .glyphicon.glyphicon-chevron-left
              =t('previous')
          -else
            %a{:href => events_list_month_path(@older.year, @older.month)}
              .glyphicon.glyphicon-chevron-left
              =t('previous')

        %li.next
          -if params[:day]
            %a{:href => events_list_day_path(@newer.year, @newer.month, @newer.day)}
              =t('next')
              .glyphicon.glyphicon-chevron-right
          -elsif params[:year] && !params[:month]
            %a{:href => events_list_year_path(@newer.year)}
              =t('next')
              .glyphicon.glyphicon-chevron-right
          -else
            %a{:href => events_list_month_path(@newer.year, @newer.month)}
              =t('next')
              .glyphicon.glyphicon-chevron-right
- @events.each do |date,event|
  -if @events[date]
    %center
      - @events[date].each do |event|
        = render 'event', event: event

app/views/events/login.html.haml
-content_for :title, t('activerecord.attributes.event.login')
.page-header
  %h2= t('activerecord.attributes.event.login')
= form_for @event, html: {id: :event, locale: current_user.language, :autocomplete => "off" }, :url => { :action => :login_update } do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .button-group.btn-group-justified
    = link_to "", {}, id: "save", :class => "btn btn-lg btn-primary navbar-btn glyphicon glyphicon-log-in"
    = link_to "", events_list_day_path(@event.start.year,@event.start.month, @event.start.day), :class => "btn btn-lg btn-primary navbar-btn glyphicon glyphicon-remove-sign"
  .field
    %p
    .input-group
      %span#pin-addon.input-group-addon= t('activerecord.attributes.user.pin')
      = text_field_tag :pin, nil, autocomplete: "off", :autofocus => true, class: "form-control input","aria-describedby" => "pin-addon"
  .field
    = f.hidden_field :login, :value => DateTime.now

  .field
    = f.submit 'Save', :style => "display: none;"

:javascript
  $(document).ready(function() {
  $('#save').on('click', function() { $('#event').submit(); });
  });

app/views/events/logout.html.haml
-content_for :title, t('activerecord.attributes.event.logout')
.page-header
  %h2= t('activerecord.attributes.event.logout')
= form_for @event, html: {id: :event, locale: current_user.language, :autocomplete => "off" }, :url => { :action => :logout_update } do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .button-group.btn-group-justified
    = link_to "", {}, id: "save", :class => "btn btn-lg btn-primary navbar-btn glyphicon glyphicon-log-out"
    = link_to "", events_list_day_path(@event.start.year,@event.start.month, @event.start.day), :class => "btn btn-lg btn-primary navbar-btn glyphicon glyphicon-remove-sign"
  .field
    %p
    .input-group
      %span#pin-addon.input-group-addon= t('activerecord.attributes.user.pin')
      = text_field_tag :pin, nil, autocomplete: "off", :autofocus => true, class: "form-control input","aria-describedby" => "pin-addon"
  .field
    = f.hidden_field :logout, :value => DateTime.now

  .field
    = f.submit 'Save', :style => "display: none;"

:javascript
  $(document).ready(function() {
  $('#save').on('click', function() { $('#event').submit(); });
  });

app/views/events/master_clinical_log.html.haml
-content_for :title, t('master_clinical_log')
.page-header
  %h2= t('master_clinical_log')
%center
  .center
    %nav{"aria-label" => "..."}
      %ul.pager
        %li.previous
          = link_to_previous_page @master_clinical_logs, "<i class='glyphicon glyphicon-chevron-left'></i> #{t('previous')}".html_safe
        %li.next
          =link_to_next_page @master_clinical_logs, "#{t('next')}<i class='glyphicon glyphicon-chevron-right'></i>".html_safe
.container
  .table-responsive
    %table.table.table-condensed.table-hover
      %tr
        %th Student Name
        %th Course #
        %th Clinical Site
        %th Unit
        %th Preceptor
        %th Date
        %th Login time
        %th Logout time
        %th Total hours
      - @master_clinical_logs.each do |master_clinical_log|
        %tr
          %td= master_clinical_log.student.name unless master_clinical_log.student.nil?
          %td= master_clinical_log.course.course.number unless master_clinical_log.course.nil?
          %td= master_clinical_log.location.clinical_site unless master_clinical_log.location.nil?
          %td= master_clinical_log.location.unit unless master_clinical_log.location.nil?
          %td= master_clinical_log.overseer.name unless master_clinical_log.overseer.nil?
          %td= l(master_clinical_log.start.to_date, format: :long) unless master_clinical_log.start.nil?
          %td= master_clinical_log.login.strftime("%H%M") unless master_clinical_log.login.nil?
          %td= master_clinical_log.logout.strftime("%H%M") unless master_clinical_log.logout.nil?
          %td= time_diff(master_clinical_log.login,master_clinical_log.logout) unless (master_clinical_log.login.nil? || master_clinical_log.logout.nil?)

app/views/events/new.html.haml
= render 'form'

app/views/events/show.html.haml
%p#notice= notice

%p
  %b Overseer:
  = @event.overseer
%p
  %b Student:
  = @event.student
%p
  %b Course:
  = @event.course
%p
  %b Start:
  = @event.start
%p
  %b Stop:
  = @event.stop
%p
  %b Login:
  = @event.login
%p
  %b Logout:
  = @event.logout

%p
  %b Location:
  = @event.location

= link_to 'Edit', edit_event_path(@event)
\|
= link_to 'Back', events_path

app/views/events/todo.html.haml
- @events.each do |event|
  =render 'event', event: event