config/routes.rb
Rails.application.routes.draw do

  resources :student_evaluation_forms
  resources :overseer_evaluation_forms
  get 'dashboard' => 'dashboard#index'
  get 'event/calendar' => 'events#calendar'
  get 'master_clinical_log' => 'events#master_clinical_log'
  get 'event/list' => 'events#list'
  get 'event/todo' => 'events#todo'
  get 'events/:id/login'  => 'events#login', as: :events_login
  patch 'events/:id/login'  => 'events#login_update', as: :events_login_update
  get 'events/:id/logout'  => 'events#logout', as: :events_logout
  patch 'events/:id/logout'  => 'events#logout_update', as: :events_logout_update
  get 'skills/:id/level_up'  => 'skills#level_up', as: :skills_level_up
  patch 'skills/:id/level_up'  => 'skills#level_up_update', as: :skills_level_up_update

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
      post :mark_as_unread
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]

  match "/event/calendar/:year/:month", :to => "events#calendar", via: [:get, :post],
        :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ },
        :as => 'events_calendar'

  match "/event/list/:year/:month/:day", :to => "events#list", via: [:get, :post],
        :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ , :day => /\d{1,2}/},
        :as => 'events_list_day'

  match "/event/list/:year/:month", :to => "events#list", via: [:get, :post],
        :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ },
        :as => 'events_list_month'

  match "/event/list/:year", :to => "events#list", via: [:get, :post],
        :constraints => { :year => /\d{4}/},
        :as => 'events_list_year'
  resources :courses
  resources :time_courses
  resources :programs
  resources :events
  resources :defined_courses
  resources :contacts, path: '/profile/contacts'
  resources :skills
  resources :defined_skills
  resources :locations  do
    get :autocomplete, :on => :collection
  end
  resources :links
  devise_for :users, path: '/profile', :controllers => {:registrations => "registrations"}
  resources :users do
    get :autocomplete, :on => :collection
    get :autocomplete_student, :on => :collection
    get :autocomplete_overseer, :on => :collection
    get :autocomplete_faculty, :on => :collection
  end

  resources :notes do
    member do
      get 'download'
    end
  end
  devise_scope :user do
    authenticated :user do
      root 'events#calendar', as: :authenticated_root
      root :to => 'events#calendar'

    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/defined_skill.rb
class DefinedSkill < ActiveRecord::Base
  has_many :skill
end

app/controllers/defined_skills_controller.rb
class DefinedSkillsController < ApplicationController
  before_action :set_defined_skill, only: [:show, :edit, :update, :destroy]

  # GET /defined_skills
  def index
    @defined_skills = DefinedSkill.all.page(params[:page]).per(16)
  end

  # GET /defined_skills/1
  def show
  end

  # GET /defined_skills/new
  def new
    @defined_skill = DefinedSkill.new
  end

  # GET /defined_skills/1/edit
  def edit
  end

  # POST /defined_skills
  def create
    @defined_skill = DefinedSkill.new(defined_skill_params)

    if @defined_skill.save
      redirect_to @defined_skill, notice: 'Defined skill was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /defined_skills/1
  def update
    if @defined_skill.update(defined_skill_params)
      redirect_to @defined_skill, notice: 'Defined skill was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /defined_skills/1
  def destroy
    @defined_skill.destroy
    redirect_to defined_skills_url, notice: 'Defined skill was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_defined_skill
      @defined_skill = DefinedSkill.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def defined_skill_params
      params.require(:defined_skill).permit(:name, :category, :required_level)
    end
end

app/helpers/defined_skills_helper.rb
module DefinedSkillsHelper
end

app/views/defined_skills/_form.html.haml
-content_for :title, t('defined_skill')
.page-header
  %h2= t('defined_skill')
= form_for @defined_skill, html: {id: :defined_skill, locale: current_user.language  } do |f|
  - if @defined_skill.errors.any?
    #error_explanation
      %h2= "#{pluralize(@defined_skill.errors.count, "error")} prohibited this defined_skill from being saved:"
      %ul
        - @defined_skill.errors.full_messages.each do |msg|
          %li= msg
  .button-group.btn-group-justified
    = link_to "", {}, id: "save", :class => "btn btn-lg btn-primary navbar-btn glyphicon glyphicon-saved"
    = link_to "", defined_skills_path, :class => "btn btn-lg btn-primary navbar-btn glyphicon glyphicon-remove-sign"
  %p
  .field
    = f.label :name
    = f.text_field :name, class: 'form-control input'
  %p
  .field
    = f.label :category
    = f.text_field :category, class: 'form-control input'
  %p
  .field
    = f.label :required_level
    = f.number_field :required_level, class: 'form-control input'
  .actions
    = f.submit 'Save', :style => "display: none;"

:javascript
  $(document).ready(function() {
  $('#save').on('click', function() { $('#defined_skill').submit(); });
  });

app/views/defined_skills/edit.html.haml
= render 'form'

app/views/defined_skills/index.html.haml
-content_for :title, t('defined_skills')
.page-header
  %h2= t('defined_skills')
.btn-group-justified
  =link_to( '', new_defined_skill_path,:class => "btn btn-lg btn-primary glyphicon glyphicon-plus-sign")
%center
  .center
    %nav{"aria-label" => "..."}
      %ul.pager
        %li.previous
          = link_to_previous_page @defined_skills, "<i class='glyphicon glyphicon-chevron-left'></i> #{t('previous')}".html_safe
        %li.next
          =link_to_next_page @defined_skills, "#{t('next')}<i class='glyphicon glyphicon-chevron-right'></i>".html_safe
%table
  - @defined_skills.each do |defined_skill|
    .panel.panel-default
      .panel-heading.clearfix
        .col-lg-6.col-md-6.col-sm-6.col-xs-6
          = link_to '', edit_defined_skill_path(defined_skill), :class => 'btn btn-lg btn-default glyphicon glyphicon-edit btn-block'
        .col-lg-6.col-md-6.col-sm-6.col-xs-6
          = link_to '', defined_skill, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-lg btn-danger glyphicon glyphicon-trash btn-block'
      .panel-body
        .row
          .col-lg-12.col-md-12.col-sm-12.col-xs-12
            Name
        .row
          .col-lg-12.col-md-12.col-sm-12.col-xs-12
            = defined_skill.name
        %p
        .row
          .col-lg-6.col-md-6.col-sm-6.col-xs-6
            Category
          .col-lg-6.col-md-6.col-sm-6.col-xs-6
            Required Level
        .row
          .col-lg-6.col-md-6.col-sm-6.col-xs-6
            = defined_skill.category
          .col-lg-6.col-md-6.col-sm-6.col-xs-6
            = defined_skill.required_level

app/views/defined_skills/new.html.haml
= render 'form'

app/views/defined_skills/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @defined_skill.name
%p
  %b Category:
  = @defined_skill.category
%p
  %b Required level:
  = @defined_skill.required_level

= link_to 'Edit', edit_defined_skill_path(@defined_skill)
\|
= link_to 'Back', defined_skills_path